services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
      
  prisma:
    image: node:18-alpine  # A lightweight Node.js image to run Prisma commands
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://postgres:admin@postgres:5432/postgres"
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npx prisma migrate dev --name init"]
