services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5433:5432
      
  prisma:
    image: node:18-alpine  # A lightweight Node.js image to run Prisma commands
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npx prisma migrate dev --name init"]
